### ISSUE TITLE
remove `require 'pry'` from intro_to_arrays_spec

### ISSUE THREAD

**Issue by loganhasson** [learn-co-curriculum/ruby-intro-to-arrays-lab#12]
shouldn't be requiring gems unless there is a Gemfile

**Comment by loganhasson** [comment]
cc @jmburges

**Comment by matbalez** [comment]
@SophieDeBenedetto FYI

Student has reported that running `learn` fails because of this.

**Comment by SophieDeBenedetto** [comment]
oops my bad, I thought I had removed that. will do.

**Comment by jmburges** [comment]
Thanks!
