### ISSUE TITLE
Learn throwing errors in this lab.

### ISSUE THREAD

**Issue by Gilmoursa** [learn-co-curriculum/ruby-intro-to-arrays-lab#13]
When I attempt to run 'learn' inside 'ruby-intro-to-arrays-lab-web-0915' I receive the following error (below). However, 'rspec' works properly.

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require': /Users/gilmoursa/.rvm/gems/ruby-2.2.0/gems/learn-co-2.5.3/lib/learn/options_sanitizer.rb:100: syntax error, unexpected ',' (SyntaxError)
    def rebuild_args!(output_file_arg:, add_test_command:)
                                       ^
/Users/gilmoursa/.rvm/gems/ruby-2.2.0/gems/learn-co-2.5.3/lib/learn/options_sanitizer.rb:185: syntax error, unexpected keyword_end, expecting end-of-input
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/gilmoursa/.rvm/gems/ruby-2.2.0/gems/learn-co-2.5.3/lib/learn.rb:6:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/gilmoursa/.rvm/gems/ruby-2.2.0/gems/learn-co-2.5.3/bin/learn:3:in `<top (required)>'
	from /Users/gilmoursa/.rvm/gems/ruby-2.2.0/bin/learn:23:in `load'
	from /Users/gilmoursa/.rvm/gems/ruby-2.2.0/bin/learn:23:in `<main>'
	from /Users/gilmoursa/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/gilmoursa/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>

**Comment by matbalez** [comment]
@loganhasson

**Comment by Gilmoursa** [comment]
I ran the learn installation suite again and everything's working. My mistake.
