### ISSUE TITLE
instantiate_new_array

### ISSUE THREAD

**Issue by msabrina** [learn-co-curriculum/ruby-intro-to-arrays-lab#19]
Trying to get #instantiate_new_array to pass...
I've tried the following;

def instantiate_new_array
  my_new_array = []
end

def instantiate_new_array
  @my_new_array = []
end

Failures:

  1) working with arrays instantiating #instantiate_new_array creates a new array and returns it
     Failure/Error: expect(@my_new_array).to be_an(Array)
       expected nil to be a kind of Array
     # ./spec/intro_to_arrays_spec.rb:15:in `block (4 levels) in <top (required)>'

  2) working with arrays instantiating #instantiate_new_array returns an array that is empty
     Failure/Error: size = @my_new_array.size
     NoMethodError:
       undefined method `size' for nil:NilClass
     # ./spec/intro_to_arrays_spec.rb:19:in`block (4 levels) in <top (required)>'

Is there something wrong with my spec file? A couple of people have tried to help me but the same exact code that gets their test to pass doesn't pass mine...

**Comment by Joll59** [comment]
@msabrina Thank you for your patience, if this problem has not been resolved. Please ask your question using Slack or the ask a question feature on Learn.co

closing issue for now.
