### ISSUE TITLE
Getting error with Learn on some (not all labs)

### ISSUE THREAD

**Issue by pkprosol** [learn-co-curriculum/ruby-intro-to-arrays-lab#20]
From my terminal, I've gotten this exact error with the gem 'specification', on a couple labs when I hit run. I updated all gems but it remains. Interestingly it's not on all labs so I assume it may have something to do with the labs or with a potential bug in learn? This time it occurred with 'ruby-intro-to-arrays-lab-000'.

(master) ruby-intro-to-arrays-lab-000
♥ learn
/Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fe3de080ce4 bundler-1.13.1> (NoMethodError)

Fully printout below:

/Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fe3de080ce4 bundler-1.13.1> (NoMethodError)
	from /Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/Home/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/rubygems_ext.rb:45:in `full_gem_path'
	from /Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/basic_specification.rb:142:in `block in full_require_paths'
	from /Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/basic_specification.rb:141:in `map'
	from /Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/basic_specification.rb:141:in `full_require_paths'
	from /Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1541:in `add_self_to_load_path'
	from /Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
	from /Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1441:in `block in activate_dependencies'
	from /Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1427:in `each'
	from /Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1427:in `activate_dependencies'
	from /Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1409:in `activate'
	from /Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1441:in `block in activate_dependencies'
	from /Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1427:in `each'
	from /Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1427:in `activate_dependencies'
	from /Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1409:in `activate'
	from /Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:68:in `block in gem'
	from /Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:67:in `synchronize'
	from /Users/Home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:67:in `gem'
	from /Users/Home/.rvm/gems/ruby-2.3.0/bin/learn:22:in `<main>'
	from /Users/Home/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Home/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by AnnJohn** [comment]
hi @pkprosol could you, for these issues too, use 'Ask a Question.' Someone will help you out directly that way and resolve the issue. thanks!
