### ISSUE TITLE
Basic Arrays

### ISSUE THREAD

**Issue by fekadesenbeta** [learn-co-curriculum/ruby-intro-to-arrays-lab#21]
Hello, i am unable to fork this lab due to the fact that i cannot find it in github.
I clicked on the link right next to the "Open IDE", but it is taking to this lab. I have also not be able to submit the last two lessons, but this one is not forking. I pulled a request for the last one.

Thank you

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like a problem with the Learn platform.

Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
